packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
